### PR TITLE
Upgrade to Asciidoctor 1.5.5-4

### PR DESCRIPTION
**Pull request by Mogztter**
Some pending issues:

* [ ] include macro is not working, how do you read file in a Brackets environnement ([XMLHttpRequest](https://developer.mozilla.org/fr/docs/Web/API/XMLHttpRequest), [fs.readFileSync](https://nodejs.org/api/fs.html#fs_fs_readfilesync_file_options))
* [ ] extensions (`diagram-extension.js`, `data-line-extension.js`) are disabled because Opal is not available
* [ ] there's a bug in Asciidoctor.js https://github.com/asciidoctor/asciidoctor.js/issues/274

### CODE REVIEW

**Comment by nerk** [comment]
Thank you very much! I tried your changes but it produces

```
Error: Unable to automatically detect the JavaScript platform, please configure Asciidoctor.js: `Asciidoctor({runtime: {platform: 'node'}})`
```

I wrote a tiny test which will probably make it easier for you to reproduce this. Just put the files attached + the asciidoctor.js files into the same directoy.

Change `test.txt` to `test.html` and `worker.txt` to `worker.js`, Fire up a local webserver and load 'test.html' in your browser.

That should reproduce the same error message in the browser's debugging console.

[worker.txt](https://github.com/asciidoctor/brackets-asciidoc-preview/files/701607/worker.txt)
[test.txt](https://github.com/asciidoctor/brackets-asciidoc-preview/files/701609/test.txt)

**Comment by nerk** [comment]
@Mogztter I just noticed that you already discovered the same problem.

**Comment by nerk** [comment]
BTW, Asciidcotor should use `XMLHttpRequest` to include files within Asciidoctor, The rendering code does not have direct access to the filesystem.

**Comment by Mogztter** [comment]
> Thank you very much! I tried your changes but it produces
> Error: Unable to automatically detect the JavaScript platform, please configure Asciidoctor.js: `Asciidoctor({runtime: {platform: 'node'}})`

> I just noticed that you already discovered the same problem.

Yes there's a bug in Asciidoctor.js, I will release a 1.5.5-5 to resolve this issue.
Once this is fixed, you should be able to configure Asciidoctor.js:

```javascript
Asciidoctor({runtime: {platform: 'browser'}})
```

> BTW, Asciidoctor should use XMLHttpRequest to include files within Brackets. The rendering code does not have direct access to the filesystem.

Ok.

**Pull request merged**
